<?php

namespace App\Http\Controllers;

use App\Models\AiConversation;
use App\Models\Plantilla;
use App\Services\AI\EmailTemplateAgent;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use Symfony\Component\HttpFoundation\StreamedResponse;

class PlantillaChatController extends Controller
{
    public function __construct(
        private EmailTemplateAgent $agent
    ) {}

    /**
     * Send a message to the AI agent and receive SSE stream.
     *
     * Note: Laravel AI doesn't support streaming with structured output.
     * We use SSE to provide immediate feedback (thinking state) while
     * the synchronous agent call processes the request.
     *
     * POST /plantilla-chat/message
     *
     * @return StreamedResponse
     */
    public function message(Request $request): StreamedResponse
    {
        $request->validate([
            'message' => ['required', 'string', 'max:2000'],
            'conversation_id' => ['nullable', 'string', 'uuid'],
        ]);

        $userId = $request->user()->id;
        $userMessage = $request->input('message');

        // Initialize agent with user's conversation
        $this->agent->forUser($userId);
        $conversation = $this->agent->getConversation();

        return new StreamedResponse(function () use ($userMessage, $conversation) {
            // Disable output buffering for real-time SSE
            if (ob_get_level()) {
                ob_end_clean();
            }

            try {
                // Emit thinking event immediately to provide feedback
                $this->emitSSE('thinking', ['content' => 'Analizando tu solicitud...']);

                // Call the agent synchronously (streaming not supported with structured output)
                $response = $this->agent->chat($userMessage);

                // Extract structured response data
                $thinking = $response['thinking'] ?? null;
                $message = $response['message'] ?? '';
                
                // Parse template from JSON string (we use template_json to avoid OpenAI schema issues)
                $templateJson = $response['template_json'] ?? '';
                $template = null;
                if ($templateJson && is_string($templateJson) && $templateJson !== '') {
                    $template = json_decode($templateJson, true);
                }

                // Emit thinking content if available
                if ($thinking) {
                    $this->emitSSE('thinking', ['content' => $thinking]);
                }

                // Emit the message
                $this->emitSSE('message', ['content' => $message]);

                // Emit template if generated
                if ($template) {
                    $this->emitSSE('template', ['content' => $template]);
                }

                // Emit done event with complete response
                $this->emitSSE('done', [
                    'conversation_id' => $conversation->id,
                    'message' => $message,
                    'template' => $template,
                ]);
            } catch (\Throwable $e) {
                Log::error('PlantillaChatController: Agent error', [
                    'error' => $e->getMessage(),
                    'trace' => $e->getTraceAsString(),
                    'user_id' => $conversation->user_id ?? null,
                ]);

                $this->emitSSE('error', [
                    'content' => 'Error procesando tu solicitud. Por favor, intenta de nuevo.',
                ]);
            }
        }, 200, [
            'Content-Type' => 'text/event-stream',
            'Cache-Control' => 'no-cache',
            'Connection' => 'keep-alive',
            'X-Accel-Buffering' => 'no', // Disable nginx buffering
        ]);
    }

    /**
     * Save a template generated by the AI.
     *
     * POST /plantilla-chat/save
     */
    public function save(Request $request): JsonResponse
    {
        $request->validate([
            'template' => ['required', 'array'],
            'template.nombre' => ['required', 'string', 'max:100'],
            'template.asunto' => ['required', 'string', 'max:200'],
            'template.componentes' => ['required', 'array', 'min:1'],
            'template.componentes.*.tipo' => ['required', 'in:logo,texto,boton,separador,imagen,footer'],
            // Component fields - all optional depending on tipo
            'template.componentes.*.id' => ['sometimes', 'string'],
            'template.componentes.*.orden' => ['sometimes', 'integer'],
            'template.componentes.*.url' => ['nullable', 'string'],
            'template.componentes.*.alt' => ['nullable', 'string', 'max:200'],
            'template.componentes.*.altura' => ['nullable', 'integer'],
            'template.componentes.*.ancho' => ['nullable', 'integer', 'min:50', 'max:600'],
            'template.componentes.*.alineacion' => ['nullable', 'string'],
            'template.componentes.*.color_fondo' => ['nullable', 'string'],
            'template.componentes.*.padding' => ['nullable', 'integer'],
            'template.componentes.*.texto' => ['nullable', 'string'],
            'template.componentes.*.tamanio_fuente' => ['nullable', 'integer'],
            'template.componentes.*.color' => ['nullable', 'string'],
            'template.componentes.*.color_texto' => ['nullable', 'string'],
            'template.componentes.*.negrita' => ['nullable', 'boolean'],
            'template.componentes.*.italica' => ['nullable', 'boolean'],
            'template.componentes.*.margen' => ['nullable', 'integer'],
            'template.componentes.*.link_url' => ['nullable', 'string', 'url'],
            'template.componentes.*.link_target' => ['nullable', 'string', 'in:_blank,_self'],
            'template.componentes.*.border_radius' => ['nullable', 'integer', 'min:0', 'max:50'],
            'template.componentes.*.enlaces' => ['nullable', 'array'],
            'existing_id' => ['nullable', 'integer', 'exists:plantillas,id'],
        ]);

        $templateData = $request->input('template');
        $existingId = $request->input('existing_id');

        // Ensure componentes have required fields
        $componentes = collect($templateData['componentes'])
            ->map(function ($componente, $index) {
                return array_merge($componente, [
                    'id' => $componente['id'] ?? 'comp-' . uniqid(),
                    'orden' => $componente['orden'] ?? $index,
                ]);
            })
            ->toArray();

        if ($existingId) {
            // Update existing template
            $plantilla = Plantilla::findOrFail($existingId);
            $plantilla->update([
                'nombre' => $templateData['nombre'],
                'asunto' => $templateData['asunto'],
                'componentes' => $componentes,
            ]);

            Log::info('PlantillaChatController: Template updated via AI', [
                'plantilla_id' => $plantilla->id,
                'user_id' => $request->user()->id,
            ]);

            return response()->json([
                'id' => $plantilla->id,
                'nombre' => $plantilla->nombre,
                'message' => 'Plantilla actualizada exitosamente',
            ]);
        }

        // Create new template
        $plantilla = Plantilla::create([
            'nombre' => $templateData['nombre'],
            'descripcion' => 'Creada con asistente de IA',
            'tipo' => 'email',
            'asunto' => $templateData['asunto'],
            'componentes' => $componentes,
            'activo' => true,
        ]);

        Log::info('PlantillaChatController: Template created via AI', [
            'plantilla_id' => $plantilla->id,
            'user_id' => $request->user()->id,
        ]);

        return response()->json([
            'id' => $plantilla->id,
            'nombre' => $plantilla->nombre,
            'message' => 'Plantilla creada exitosamente',
        ], 201);
    }

    /**
     * Get conversation history for the authenticated user.
     *
     * GET /plantilla-chat/history
     */
    public function history(Request $request): JsonResponse
    {
        $userId = $request->user()->id;

        $conversation = AiConversation::where('user_id', $userId)->first();

        if (! $conversation) {
            return response()->json([
                'messages' => [],
                'current_template' => null,
            ]);
        }

        return response()->json([
            'messages' => $conversation->messages ?? [],
            'current_template' => $conversation->current_template,
        ]);
    }

    /**
     * Clear conversation history for the authenticated user.
     *
     * DELETE /plantilla-chat/history
     */
    public function clearHistory(Request $request): JsonResponse
    {
        $userId = $request->user()->id;

        $conversation = AiConversation::where('user_id', $userId)->first();

        if ($conversation) {
            $conversation->clearHistory();
            $conversation->save();

            Log::info('PlantillaChatController: History cleared', [
                'user_id' => $userId,
            ]);
        }

        return response()->json([
            'message' => 'Historial de conversación eliminado',
        ]);
    }

    /**
     * Emit a Server-Sent Event.
     */
    private function emitSSE(string $type, array $data): void
    {
        $payload = array_merge(['type' => $type], $data);
        echo 'data: ' . json_encode($payload) . "\n\n";

        // Flush output immediately
        if (ob_get_level()) {
            ob_flush();
        }
        flush();
    }
}
